"""Add project type field to external order

Revision ID: 006_add_project_type_to_external_order
Revises: 5c8c9d6a07c1
Create Date: 2023-12-16 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006_add_proj_type_ext_order'
down_revision = '5c8c9d6a07c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可为空的列
    op.add_column('external_order', sa.Column('project_type', sa.String(), nullable=True))
    # 为现有记录设置默认值
    op.execute("UPDATE external_order SET project_type = 'default' WHERE project_type IS NULL")
    # 现在将列设为非空
    op.alter_column('external_order', 'project_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_order', 'project_type')
    # ### end Alembic commands ###